# Generated by Django 5.0.4 on 2024-04-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("website", models.URLField()),
                ("contact", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=100)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "FIksi"), (2, "Non-Fiksi")]
                    ),
                ),
                (
                    "sub_category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Novel"),
                            (2, "Komik"),
                            (3, "Sains, Matematika dan Enginnering"),
                            (4, "HUmaniora"),
                            (5, "Biografi"),
                            (6, "Pendidikan"),
                            (7, "Agama"),
                            (8, "Psikologi"),
                            (4, "HUmanioran"),
                            (10, "Pertanian"),
                            (11, "Journal"),
                        ]
                    ),
                ),
                ("url_buku", models.URLField()),
                ("url_image", models.URLField()),
                ("stok", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.author",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("rating", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_page.book"
                    ),
                ),
            ],
        ),
    ]
