# Generated by Django 5.0.4 on 2024-04-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0004_author_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="url_buku",
            field=models.FileField(upload_to="buku/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="url_image",
            field=models.ImageField(null=True, upload_to="image/"),
        ),
    ]
