# Generated by Django 5.0.4 on 2024-04-23 09:03

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auths", "0001_initial"),
        ("main_page", "0002_alter_book_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaftarKunjungan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("masuk", models.DateTimeField()),
                ("keluar", models.DateTimeField()),
                (
                    "anggota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auths.usersima"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DaftarPinjam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("tgl_pinjam", models.DateTimeField()),
                ("tgl_kembali", models.DateTimeField()),
                ("status", models.BooleanField(default=False)),
                ("keterangan", models.TextField(default="", null=True)),
                (
                    "anggota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auths.usersima"
                    ),
                ),
                (
                    "buku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_page.book"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
