# Generated by Django 5.0.4 on 2024-04-23 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_anggota", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(default="", max_length=254, null=True)),
                ("alamat", models.TextField()),
                ("mobile_phone", models.CharField(max_length=100)),
                (
                    "jenis_kelamin",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pria"), (2, "Wanita")]
                    ),
                ),
                (
                    "pekerjaan",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ASN"),
                            (2, "Swasta"),
                            (3, "Mahasiswa"),
                            (4, "Pelajar"),
                            (5, "Wiraswasta"),
                            (6, "Pegawai Negara Non ASN"),
                            (7, "Other"),
                        ]
                    ),
                ),
                (
                    "pendidikan",
                    models.PositiveBigIntegerField(
                        choices=[
                            (1, "TK"),
                            (2, "SD"),
                            (3, "SMP"),
                            (4, "SMA"),
                            (5, "D3"),
                            (6, "S1"),
                            (7, "S2"),
                            (8, "S3"),
                            (9, "Other"),
                        ]
                    ),
                ),
                (
                    "tipe",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Admin"), (2, "Regular"), (3, "Premium")]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
