# Generated by Django 5.0.4 on 2024-04-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0002_usersima_tanggal_lahir"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersima",
            name="nip",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
